# Sample config for Prometheus.

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'spin'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['192.168.1.32:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  - job_name: 'prometheus'
    #metrics_path: /prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['192.168.1.32:9090']

  - job_name: 'horn.local'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['192.168.1.36:9100', '192.168.1.37:9100']

  - job_name: 'web01.local'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['192.168.1.18:9100', '192.168.1.19:9100']

  - job_name: 'web02.local'
    scrape_interval: 15s
    scrape_timeout: 10s

    static_configs:
      - targets: ['192.168.1.20:9100', '192.168.1.21:9100']

#  - job_name: '7pi.local'
#    scrape_interval: 15s
#    scrape_timeout: 10s
#    static_configs:
#      - targets: ['192.168.1.17:9100']

  - job_name: 'spinorama.prod'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['192.168.1.19:9113']

  - job_name: 'spin.local'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['192.168.1.32:9100', '192.168.1.33:9100','192.168.1.34:9100']

  - job_name: 'ping'
    scrape_interval: 15s
    scrape_timeout:  3s
    static_configs:
      - targets:
        - 192.168.1.32
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.32:9374 # This exporter's real hostname:port

  - job_name: 'coinmarketcap'
    scrape_interval: 5m
    scrape_timeout:  30s
    static_configs:
      - targets: ['192.168.1.32:9101']

  - job_name: 'mktxp'
    static_configs:
      - targets: ['192.168.1.32:49090']

# currently not working
#  - job_name: 'hpssa'
#    static_configs:
#      - targets: ['192.168.1.36:49100']

  - job_name: 'nvidia'
    static_configs:
      - targets: ['192.168.1.36:9835']

  - job_name: 'rpc-node-polkadot'
    static_configs:
      - targets: ['192.168.1.36:9615']

  - job_name: 'grafana'
    static_configs:
      - targets: ['192.168.1.32:3000']

  - job_name: 'amdgpu'
    scrape_interval: 1m
    scrape_timeout:  15s
    metrics_path: '/probe'
    params:
      script: ['amdgpu']
    static_configs:
      - targets: ['192.168.1.32:9469']

  - job_name: 'speedtest'
    scrape_interval: 1h
    scrape_timeout:  120s
    metrics_path: '/probe'
    params:
      script: ['speedtest']
    static_configs:
      - targets: ['192.168.1.32:9469']

