tls:
  enabled: false
  crt: server.crt
  key: server.key

basicAuth:
  enabled: false
  username: admin
  password: admin

bearerAuth:
  enabled: false
  signingKey: my_secret_key

scripts:
  - name: amdgpu
    command: /home/pierre/scrapers/conf/script_exporter/amdgpu.py
  - name: speedtest
    command: /home/pierre/scrapers/conf/script_exporter/speedtest.sh
    timeout:
      max_timeout: 120
    cacheDuration: 18000
